export const movieKeywords = [
  "action movies",
  "comedy movies",
  "drama movies",
  "horror movies",
  "romantic movies",
  "Tom Hanks movies",
  "Jennifer Lawrence movies",
  "Brad Pitt movies",
  "Steven Spielberg movies",
  "Christopher Nolan movies",
  "Quentin Tarantino movies",
  "sci-fi movies",
  "romantic comedies",
  "animated movies",
  "documentaries",
  "2010 movies",
  "1990s movies",
  "new releases",
  "movies set in New York",
  "zombie movies",
  "time travel movies",
  "Oscar-winning movies",
  "Palme d'Or winners",
  "Sundance Film Festival winners",
];
